export const PRODUCT_ADD = "PRODUCT_ADD";
export const PRODUCT_LOADING = "PRODUCT_LOADING";
export const PRODUCT_FAILED = "PRODUCT_FAILED";
export const PRODUCT_FIND = "PRODUCT_FIND";
export const PRODUCT_FILTER = "PRODUCT_FILTER";

export const ADD_TO_CART = "ADD_TO_CART";
export const DELETE_FROM_CART = "DELETE_FROM_CART";

export const BRAND_ADD = "BRAND_ADD";
export const BRAND_LOADING = "BRAND_LOADING";
export const BRAND_FAILED = "BRAND_FAILED";

export const CATEGORY_ADD = "CATEGORY_ADD";
export const CATEGORY_LOADING = "CATEGORY_LOADING";
export const CATEGORY_FAILED = "CATEGORY_FAILED";
