export const PRODUCTS_ADD = "PRODUCTS_ADD";
export const PRODUCT_ADD = "PRODUCT_ADD";
export const PRODUCT_LOADING = "PRODUCT_LOADING";
export const PRODUCT_FAILED = "PRODUCT_FAILED";
export const PRODUCT_FIND = "PRODUCT_FIND";
export const PRODUCT_FILTER = "PRODUCT_FILTER";
export const GET_PRODUCT_NAME = "GET_PRODUCT_NAME";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const PRODUCT_UPDATE = "PRODUCT_UPDATE";

export const ADD_TO_CART = "ADD_TO_CART";
export const DELETE_FROM_CART = "DELETE_FROM_CART";
export const ADD_COUNT = "ADD_COUNT";
export const REMOVE_COUNT = "REMOVE_COUNT";

export const BRAND_ADD = "BRAND_ADD";
export const BRAND_LOADING = "BRAND_LOADING";
export const BRAND_FAILED = "BRAND_FAILED";
export const BRAND_UPDATE = "BRAND_UPDATE";
export const BRAND_DELETE = "BRAND_DELETE";

export const CATEGORIES_ADD = "CATEGORIES_ADD";
export const CATEGORY_ADD = "CATEGORY_ADD";
export const CATEGORY_LOADING = "CATEGORY_LOADING";
export const CATEGORY_FAILED = "CATEGORY_FAILED";
export const CATEGORY_DELETE = "CATEGORY_DELETE";
export const CATEGORY_UPDATE = "CATEGORY_UPDATE";

export const QUESTIONS_ADD = "QUESTIONS_ADD";
export const QUESTION_ADD = "QUESTION_ADD";
export const QUESTION_LOADING = "QUESTION_LOADING";
export const QUESTION_FAILED = "QUESTION_FAILED";
export const QUESTION_UPDATE = "QUESTION_UPDATE";

export const GET_USER = "GET_USER";
